# Generated by Django 5.1.7 on 2025-04-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remind_by', models.DateTimeField()),
                ('is_reminder_complete', models.BooleanField(default=False)),
                ('rem_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
